SRCS := btfp.c bus_if.h device_if.h pci_if.h btfp.h ACEiii.h
KMOD := btfp

.include <bsd.kmod.mk>

_clean clean_ cleanup distclean:
	rm -f .depend.btfp.o *.o core *.core

install: btfp.ko
	cp btfp.ko /boot/kernel/btfp.ko
	-kldunload btfp
	kldload btfp
